### ISSUE TITLE
Target [App\Interfaces\User\UserInterface] is not instantiable while building 

### ISSUE THREAD

**Issue by alaksandarjesus** [felicianopj/laravel-repository-tutorial#1]
Hi..
Thanks for the tutorial. I was following your code and I am getting

`BindingResolutionException in Container.php line 873:
Target [App\Interfaces\User\UserInterface] is not instantiable while building [App\Http\Controllers\UserController]`

I even cross checked this sample project with mine, and everything fits in its place. Let me know to test why its not instatiating.

**Comment by alaksandarjesus** [comment]
Previous Code
`$this->app->bind('App\Repositories\User\UserRepository', 'App\Interfaces\User\UserInterface')`
Working Code
`$this->app->bind('App\Interfaces\User\UserInterface','App\Repositories\User\UserRepository')`

I actually loaded UserRepository first and that was the error. Thanks for that clean tutorial.

**Comment by besabellacyrus** [comment]
So interface first before the repository?  'App\Interfaces\User\UserInterface','App\Repositories\User\UserRepository'

I am experiencing this one two, and follow this, but did not work.

**Comment by besabellacyrus** [comment]
Ok my bad, I thought is you can put multiple in one binding, 

Previous Code
```
$this->app->bind(
            ExpenseRepositoryInterface::class,
            ExpenseRepository::class,
            PropertyRepositoryInterface::class,
            PropertyRepository::class
        );
```

Working Code 
```
$this->app->bind(
            ExpenseRepositoryInterface::class,
            ExpenseRepository::class,
        );

        $this->app->bind(
            PropertyRepositoryInterface::class,
            PropertyRepository::class
        );
```

**Comment by cassianobrexbit** [comment]
> Ok my bad, I thought is you can put multiple in one binding,
> 
> Previous Code
> 
> ```
> $this->app->bind(
>             ExpenseRepositoryInterface::class,
>             ExpenseRepository::class,
>             PropertyRepositoryInterface::class,
>             PropertyRepository::class
>         );
> ```
> 
> Working Code
> 
> ```
> $this->app->bind(
>             ExpenseRepositoryInterface::class,
>             ExpenseRepository::class,
>         );
> 
>         $this->app->bind(
>             PropertyRepositoryInterface::class,
>             PropertyRepository::class
>         );
> ```

Holy shit, I had the same problem as you. Thanks!

**Comment by cassianobrexbit** [comment]
> Ok my bad, I thought is you can put multiple in one binding,
> 
> Previous Code
> 
> ```
> $this->app->bind(
>             ExpenseRepositoryInterface::class,
>             ExpenseRepository::class,
>             PropertyRepositoryInterface::class,
>             PropertyRepository::class
>         );
> ```
> 
> Working Code
> 
> ```
> $this->app->bind(
>             ExpenseRepositoryInterface::class,
>             ExpenseRepository::class,
>         );
> 
>         $this->app->bind(
>             PropertyRepositoryInterface::class,
>             PropertyRepository::class
>         );
> ```

Holy shit, I got stuck in the same problem. Thanks!

**Comment by hemantsan** [comment]
> Ok my bad, I thought is you can put multiple in one binding,
> 
> Previous Code
> 
> ```
> $this->app->bind(
>             ExpenseRepositoryInterface::class,
>             ExpenseRepository::class,
>             PropertyRepositoryInterface::class,
>             PropertyRepository::class
>         );
> ```
> 
> Working Code
> 
> ```
> $this->app->bind(
>             ExpenseRepositoryInterface::class,
>             ExpenseRepository::class,
>         );
> 
>         $this->app->bind(
>             PropertyRepositoryInterface::class,
>             PropertyRepository::class
>         );
> ```

Best Answer

**Comment by nandpalmohit** [comment]
> Previous Code `$this->app->bind('App\Repositories\User\UserRepository', 'App\Interfaces\User\UserInterface')` Working Code `$this->app->bind('App\Interfaces\User\UserInterface','App\Repositories\User\UserRepository')`
> 
> I actually loaded UserRepository first and that was the error. Thanks for that clean tutorial.

Woah, I got stuck in the same problem. Thanks for sharing.

**Comment by Shantanu-Bajaj** [comment]
Still not working
